### ISSUE TITLE
How to compile the latest linux kernel 5.19.12?

### ISSUE THREAD

**Issue by QGB** [JasonFreeLab/HiSTBLinuxV100R005C00SPC050#1]
linux-5.19.12 for hisilicon

**Comment by JasonFreeLab** [comment]
Hisilicon is currently only supported up to Linux kernel 4.4.x.

**Comment by 185264646** [comment]
You can do the porting work yourself. But no work done for now. It's not so hard anyway, hisilicon has made a hi3798cv200-poplar support in mainline kernel. You may use the dts and drivers for that to help you support other hisilicon soc(such as hi3798mv100/200(H)/300 and etc). Just compare the dts in this repository to the dts in mainline repository and do some other work.
